using ConvoContentBuddy.Data.Entities;

namespace ConvoContentBuddy.Data.Repositories;

/// <summary>
/// Repository interface for <see cref="Problem"/> persistence operations.
/// </summary>
public interface IProblemRepository
{
    /// <summary>
    /// Upserts a problem based on its <see cref="Problem.Slug"/>.
    /// Creates a new record if the slug does not exist; updates the existing record otherwise.
    /// </summary>
    /// <remarks>
    /// This method persists only the scalar fields of <paramref name="problem"/>.
    /// The <see cref="Problem.ProblemTags"/> navigation collection is <b>not</b> persisted
    /// by this method. Use <see cref="IProblemTagRepository.SyncTagsAsync"/> to synchronize
    /// tag associations after upserting the problem.
    /// </remarks>
    /// <param name="problem">The problem entity to upsert.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The persisted <see cref="Problem"/> entity.</returns>
    Task<Problem> UpsertBySlugAsync(Problem problem, CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns problems whose embedding is <c>null</c> or was generated by a different model/dimension pair.
    /// </summary>
    /// <param name="modelName">Target embedding model name.</param>
    /// <param name="dimensions">Target embedding dimensions.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Problems that need (re-)embedding.</returns>
    Task<IReadOnlyList<Problem>> GetUnembeddedForProfileAsync(
        string modelName,
        int dimensions,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates embedding data and provenance fields for the specified problem.
    /// </summary>
    /// <param name="problemId">The ID of the problem to update.</param>
    /// <param name="embedding">The new vector embedding.</param>
    /// <param name="modelName">The model that produced the embedding.</param>
    /// <param name="dimensions">The number of dimensions in the embedding.</param>
    /// <param name="generatedAt">When the embedding was generated.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task UpdateEmbeddingAsync(
        Guid problemId,
        Pgvector.Vector embedding,
        string modelName,
        int dimensions,
        DateTimeOffset generatedAt,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns the total number of problems in the store.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<int> CountAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns problems ordered by cosine similarity to <paramref name="queryVector"/>,
    /// filtered to embeddings produced by the specified model and dimensions.
    /// </summary>
    /// <param name="queryVector">The query vector to compare against.</param>
    /// <param name="modelName">Embedding model name to filter by.</param>
    /// <param name="dimensions">Embedding dimensions to filter by.</param>
    /// <param name="limit">Maximum number of results to return.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<IReadOnlyList<Problem>> SearchByVectorAsync(
        Pgvector.Vector queryVector,
        string modelName,
        int dimensions,
        int limit,
        CancellationToken cancellationToken = default);
}
